export const ROUTES = {
  HOME: "/",
  SHOP: "/shop",
  DISCOVER: "/discover",
  CATEGORIES: "/categories",
  ABOUT: "/about",
  CONTACT: "/contact",
  CART: "/cart",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  SETTINGS: "/settings",
  ACCOUNT: "/account",
  ORDERS: "/orders",
  ADMIN: "/admin",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_CREATE_PRODUCT: "/admin/products/new",
};
