import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import { Providers } from "@/components/Providers/Providers";
import { CookieConsentDialog } from "@/components/CookiesConsent/CookiesConsent";

//TODO change name to be dynamic based on the project name
export const metadata: Metadata = {
  title: "Create Ecommerce App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body>
        <Providers>
          <Navbar />
          {children}
          <CookieConsentDialog />
        </Providers>
      </body>
    </html>
  );
}
